spring:
  datasource:
    url: jdbc:mysql://centos:3306/crawler-webmagic?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 4321red@zz
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: com/feng/crawlerwebmagic/**/mapping/*.xml
  type-aliases-package: com.feng.crawlerwebmagic.**.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: AUTO
      table-underline: true
